//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int UserID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string AaadharNo { get; set; }
        public string PAN { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Salary { get; set; }
        public string UserImg { get; set; }
    
        public virtual District District { get; set; }
        public virtual Login Login { get; set; }
    }
}
